import uuid
from typing import Any

import pytest
from alembic import command
from sqlalchemy import func, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Listing, ListingType
from tests.integration.conftest import alembic_config

pytestmark = pytest.mark.integration


def make_listing(**overrides: Any) -> Listing:
    fields: dict[str, Any] = {
        "title": "2 bedroom flat in Lekki Phase 1",
        "price": 350_000_000,  # ₦3,500,000 in kobo
        "listing_type": ListingType.RENT,
        "bedrooms": 2,
        "location": "SRID=4326;POINT(3.4746 6.4474)",  # lng lat
        "city": "Lagos",
        "agent_id": uuid.uuid4(),
    }
    return Listing(**(fields | overrides))


async def test_server_defaults_and_location_round_trip(db_session: AsyncSession) -> None:
    listing = make_listing()
    db_session.add(listing)
    await db_session.commit()

    assert isinstance(listing.id, uuid.UUID)
    assert listing.currency == "NGN"
    assert listing.created_at is not None
    assert listing.updated_at == listing.created_at

    row = (
        await db_session.execute(
            text("SELECT ST_X(location::geometry), ST_Y(location::geometry) FROM listings")
        )
    ).one()
    assert tuple(row) == pytest.approx((3.4746, 6.4474))


async def test_listing_type_stored_as_lowercase_enum_label(db_session: AsyncSession) -> None:
    db_session.add(make_listing(listing_type=ListingType.SHORTLET))
    await db_session.commit()

    raw = await db_session.scalar(text("SELECT listing_type::text FROM listings"))
    assert raw == "shortlet"


async def test_updated_at_trigger_bumps_on_update(db_session: AsyncSession) -> None:
    listing = make_listing()
    db_session.add(listing)
    await db_session.commit()
    created_at = listing.created_at

    listing.title = "Renovated 2 bedroom flat"
    await db_session.commit()

    assert listing.updated_at > created_at
    assert listing.created_at == created_at


@pytest.mark.parametrize(
    ("overrides", "constraint"),
    [
        ({"price": 0}, "ck_listings_price_positive"),
        ({"price": -100}, "ck_listings_price_positive"),
        ({"bedrooms": -1}, "ck_listings_bedrooms_non_negative"),
    ],
)
async def test_check_constraints(
    db_session: AsyncSession, overrides: dict[str, Any], constraint: str
) -> None:
    db_session.add(make_listing(**overrides))

    with pytest.raises(IntegrityError, match=constraint):
        await db_session.commit()


async def test_studio_with_zero_bedrooms_is_allowed(db_session: AsyncSession) -> None:
    db_session.add(make_listing(bedrooms=0))
    await db_session.commit()

    assert await db_session.scalar(select(func.count()).select_from(Listing)) == 1


def test_models_match_migrations(migrated_database: str) -> None:
    # Raises AutogenerateDiffsDetected if models and migrations have drifted,
    # including spurious GeoAlchemy2 spatial-index diffs.
    command.check(alembic_config(migrated_database))
