import asyncio
from logging.config import fileConfig
from typing import Any

from alembic import context
from geoalchemy2 import alembic_helpers
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from app.core.config import get_settings
from app.db.models import Base

config = context.config

# Callers that manage logging themselves (e.g. the test suite) can opt out.
if config.config_file_name is not None and config.attributes.get("configure_logger", True):
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url() -> str:
    # An explicit sqlalchemy.url (set programmatically, e.g. by tests) wins over settings.
    return config.get_main_option("sqlalchemy.url") or get_settings().database_url


def include_name(name: str | None, type_: str, parent_names: dict[str, Any]) -> bool:
    # Only reflect tables we model. This skips PostGIS spatial_ref_sys and the image's
    # tiger/topology tables, so autogenerate never proposes dropping them.
    if type_ == "table":
        return name in target_metadata.tables
    return True


def include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    # Belt and braces for anything include_name lets through.
    return not (type_ == "table" and reflected and compare_to is None)


def _configure_kwargs() -> dict[str, Any]:
    return {
        "target_metadata": target_metadata,
        "include_name": include_name,
        "include_object": include_object,
        # Renders GeoAlchemy2 types (and adds `import geoalchemy2`) in autogenerated files.
        "render_item": alembic_helpers.render_item,
    }


def run_migrations_offline() -> None:
    context.configure(
        url=get_url(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_configure_kwargs(),
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, **_configure_kwargs())
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = create_async_engine(get_url(), poolclass=pool.NullPool)
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
